### ISSUE TITLE
Unable to view demo

### ISSUE THREAD

**Issue by brianholle** [vivin/pdfjs-text-selection-demo#4]
I am unable to view the document in your demo. When I render the page, It just shows the text and a box outline, with no pdf shown. 

I know this is an old project, but I am really struggling with the implementation of pdf.js text layer. Anything will help.

Thanks

**Comment by vivin** [comment]
@brianholle This is a based off a very old version of pdfjs and is not maintained anymore. pdfjs has undergone major changes since I wrote this, so you're likely to be more successful by using their examples.
